apiVersion: v1
kind: ConfigMap
metadata:
  name: vladexconfigmap
data:
  config.json: |
    {
      
      "APP_USERNAME": "usernameTM87",
      
      "APP_PASSWORD": "password123456"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example-session-4-vladex
spec:
  containers:
  - name: vladexcontainer
    image: brunoteleginski/node-session-4-task
    volumeMounts:
    - name: vol2
      mountPath: "/usr/src/app/config"
      readOnly: true
    ports:
    - containerPort: 3001
  volumes:
  - name: vol2
    configMap:
      name: vladexconfigmap
