apiVersion: v1
kind: ConfigMap
metadata:
  name: vladexconfigmap
data:
  configuration.json: |
    {  
    "yourname": "Vladimir",
    "surname": "Pavicic",
    "town": "Rotterdam"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-example-session-4-vladex
spec:
  containers:
  - name: vladexcontainer
    image: brunoteleginski/node-session-4-task
    env:
      - name: APP_USERNAME
        valueFrom:
          secretKeyRef:
            name: vladexsecret
            key: username
            optional: false

      - name: APP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: vladexsecret
            key: password
            optional: false
    volumeMounts:
    - name: vol2
      mountPath: "/var/www/html/configuration"
      readOnly: true
    ports:
    - containerPort: 3001
  volumes:
  - name: vol2
    configMap:
      name: vladexconfigmap
