apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brunospace
  name: bruno-deployment
  labels:
    app: app1 # This label is to connect service
spec:
  replicas: 3         # replica
  selector:
    matchLabels:
      app: bronx                        # **** Replica label need's to match Pod label
  template:           # Pod level         
    metadata:
      labels:
        app: bronx                      # **** Pod label
    spec:
      containers:    

      - name: container1                 # 1st container
        image: brunoteleginski/nodejs-application
        ports:
        - containerPort: 3001

        volumeMounts:
          - name: mypd                          
            mountPath: /persist-data

      volumes:       #**************** Volume
      - name: mypd                              
        persistentVolumeClaim:
          claimName: pv-claim-002
        




