apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: brunospace
  name: bruno-deployment
  labels:
    app: bronx # This label is to connect service
spec:
  replicas: 3         # replica
  selector:
    matchLabels:
      app: bronx                        # **** Replica label need's to match Pod label
  template: #********** Pod level         
    metadata:
      labels:
        app: bronx                      # **** Pod label
    spec:
      containers:    

      - name: container1                 # 1st container
        image: brunoteleginski/nodejs-application
        ports:
        - containerPort: 3001
       # command: ['sh', '-c', 'mv /var/www/html/logs/application.log /persist-data && sleep 50000']

        volumeMounts:
          - name: mypd                          
            mountPath: /persist-data

      - name: side-container                 # 1st container
        image: nginx
        ports:
        - containerPort: 80

        volumeMounts:
          - name: mypd                          
            mountPath: /persist-data


      volumes:       #**************** Volume
      - name: mypd                              
        persistentVolumeClaim:
          claimName: pv-claim-002

---

apiVersion: v1
kind: Service
metadata:
  namespace: brunospace
  name: service4
spec:
  selector:
    app: bronx           # connection label for service
  ports:
    - name: protocol1   # channell 1 on service for mongodB connection
      protocol: TCP
      port: 27017
      targetPort: 27017

    - name: protocol2   # channell 2 on service for NodeJS app connection
      protocol: TCP
      port: 80
      targetPort: 80
 
    - name: protocol3   # channell 3 on service for Nginx-sidecontainer app connection
      protocol: TCP
      port: 3001
      targetPort: 3001
        




