apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: brunospace
  name: pv-claim-002
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
