

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: brunospace
  name: bruno-mongodb-deployment
  labels:
    app: bronx 
spec:
  serviceName: "service4"    # connecting with servise using "real service name"
  replicas: 3       
  selector:
    matchLabels:
      app: app2                        # **** Replica label need's to match Pod label
  template:           # Pod level         
    metadata:
      labels:
        app: app2                      # **** Pod label
    spec:
      containers:    

      - name: container-mongodb                 # 1st container
        image: bitnami/mongodb
        ports:
        - containerPort: 27017