apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task3
  name: nginx-deployment
  labels:
    app: nginx # This label is not mandatory 
spec:
  replicas: 3         # replica
  selector:
    matchLabels:
      app: nginx                        # **** Replica label need's to match Pod label
  template:           # Pod level         
    metadata:
      labels:
        app: nginx                      # **** Pod label
    spec:
      containers:    

      - name: container1                 # 1st container
        image: nginx
        ports:
        - containerPort: 3001
        command: ['sh', '-c', 'echo "ola amigos  from container 1" >> /shared-folder/container1.txt; sleep 50000']
 
     #  command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        volumeMounts:
          - name: config-vol #**
            mountPath: /shared-folder

      - name: container2                # 2nd container
        image: nginx
        ports:
        - containerPort: 80
        command: ['sh', '-c', 'echo "container 2 wrote it!" >> /shared-folder/container1.txt; sleep 50000']
        volumeMounts:
          - name: config-vol #**
            mountPath: /shared-folder

      - name: container3                # 3rd container
        image: nginx
        ports:
        - containerPort: 3007
        command: ['sh', '-c', 'mv /shared-folder/container1.txt /persist-data && sleep 50000']
        volumeMounts:
          - name: config-vol #**
            mountPath: /shared-folder

          - name: mypd
            mountPath: /persist-data

      - name: container4                # 4th container
        image: nginx
        ports:
        - containerPort: 3009
        command: ['sh', '-c', 'cat /persist-data/container1.txt  && sleep 50000']
        volumeMounts:
          - name: mypd                          #****
            mountPath: /persist-data

      volumes:
      - name: config-vol #** 
        emptyDir: {} 
    
      - name: mypd                              #****
        persistentVolumeClaim:
          claimName: task-pv-claim 

---

apiVersion: v1
kind: Service
metadata:
  namespace: task3
  name: service3
spec:
  selector:
    app: nginx
  ports:
    - name: protocol1   # channel 1 on service
      protocol: TCP
      port: 81
      targetPort: 3001

    - name: protocol2  # channel 2 on service
      protocol: TCP
      port: 80
      targetPort: 80

    - name: protocol3  # channel 3 on service
      protocol: TCP
      port: 82
      targetPort: 3007

    - name: protocol4  # channel 4 on service
      protocol: TCP
      port: 83
      targetPort: 3009


