apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task3
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3         # replica
  selector:
    matchLabels:
      app: nginx
  template:           # Pod         
    metadata:
      labels:
        app: nginx
    spec:
      containers:

      - name: container1           # 1st container
        image: vladex007/vladex007repository:latest
        ports:
        - containerPort: 3001
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

      - name: container2                # 2nd container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

      - name: container3                # 2nd container
        image: nginx:1.14.2
        ports:
        - containerPort: 81
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

      - name: container4                # 2nd container
        image: nginx:1.14.2
        ports:
        - containerPort: 83
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]



---

apiVersion: v1
kind: Service
metadata:
  namespace: task3
  name: service3
spec:
  selector:
    app: nginx
  ports:
    - name: protocol1   # channel 1 on service
      protocol: TCP
      port: 81
      targetPort: 3001

    - name: protocol2  # channel 2 on service
      protocol: TCP
      port: 80
      targetPort: 80

    - name: protocol3  # channel 3 on service
      protocol: TCP
      port: 82
      targetPort: 3007

    - name: protocol4  # channel 4 on service
      protocol: TCP
      port: 83
      targetPort: 3009
