apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: task3
  name: task-pv-claim
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
