apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: task2
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
         labels:
          cjob: cronjob
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; "apk --no-cache add curl; while true; do sleep 60; curl 'https://google.com'; done" 
          restartPolicy: OnFailure