apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: task2
  name: hello

spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
     template:
       metadata:
        labels:
         cj2job: cronjob
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure