apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: task2
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
         labels:
          cjob: cronjob
        spec:
          containers:
          - name: hello
            image: alpine:3.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster; curl service; curl service:81
          restartPolicy: OnFailure