apiVersion: v1
kind: Service
metadata:
  namespace: task2
  name: service
spec:
  selector:
    app: nginx
  ports:
    - name: protocol1   # channel 1 on service
      protocol: TCP
      port: 81
      targetPort: 3001

    - name: protocol2  # channel 2 on service
      protocol: TCP
      port: 80
      targetPort: 80