apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task2
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3         # replica
  selector:
    matchLabels:
      app: nginx
  template:           # Pod         
    metadata:
      labels:
        app: nginx
    spec:
      containers:

      - name: container1           # 1st container
        image: vladex007/vladex007repository:latest
        ports:
          - containerPort: 3001

      - name: nginx                # 2nd container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
