apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: task2
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:

      - name: nginx                # 1st container
        image: nginx:1.14.2
        ports:
        - containerPort: 80

      - name: container2           # 2nd container
        image: vladex007/vladex007repository:latest
        ports:
          - containerPort: 3001