apiVersion: v1
kind: Service
metadata:
  namespace: task2
  name: service
spec:
  selector:
    app: nginx
  ports:
    - name: http   # channel 1 on service
      protocol: TCP
      port: 80
      targetPort: 9376

    - name: https  # channel 2 on service
      protocol: TCP
      port: 443
      targetPort: 9377