apiVersion: v1
kind: Pod
metadata:
  namespace: task1
  name: pod1
  labels:
    app: deploy1
spec:
  containers:
  - name: container1
    image: kennethreitz/httpbin
    ports:
      - containerPort: 8081
        
  